# Generated by Django 4.2.30 on 2026-08-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('area', models.FloatField()),
                ('electricity_price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('water_price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('deposit', models.DecimalField(decimal_places=0, max_digits=12)),
                ('floor', models.IntegerField(default=1)),
                ('max_people', models.IntegerField(default=1)),
                ('has_wifi', models.BooleanField(default=False)),
                ('has_air_conditioner', models.BooleanField(default=False)),
                ('has_bed', models.BooleanField(default=False)),
                ('has_tv', models.BooleanField(default=False)),
                ('has_refrigerator', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms/')),
                ('status', models.CharField(choices=[('available', 'Đang trống'), ('rented', 'Đã cho thuê'), ('reserved', 'Đang giữ chỗ')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
