# Generated by Django 4.2.30 on 2026-08-12 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_city_district_ward_room_city_room_district_room_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ward',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wards', to='rooms.city'),
        ),
        migrations.AddField(
            model_name='ward',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ward',
            name='ward_type',
            field=models.CharField(choices=[('commune', 'Xã'), ('ward', 'Phường'), ('special', 'Đặc khu')], default='commune', max_length=20),
        ),
    ]
