# Generated by Django 4.2.30 on 2026-08-12 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_city_code_ward_city_ward_code_ward_ward_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wards', to='rooms.district'),
        ),
    ]
