# Generated by Django 4.2.30 on 2026-08-12 01:56

from django.db import migrations

def populate_ward_city(apps, schema_editor):

    Ward = apps.get_model('rooms', 'Ward')

    for ward in Ward.objects.filter(
        city__isnull=True,
        district__isnull=False
    ):
        ward.city_id = ward.district.city_id
        ward.save(update_fields=['city'])

class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_ward_district'),
    ]

    operations = [
        migrations.RunPython(
            populate_ward_city,
            migrations.RunPython.noop
        ),
    ]
