# Generated by Django 4.2.30 on 2026-08-12 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_populate_ward_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='district',
        ),
    ]
