# Generated by Django 4.2.30 on 2026-08-26 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_roomimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'permissions': [('view_dashboard', 'Can view dashboard')]},
        ),
    ]
