# Generated by Django 4.2.30 on 2026-09-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_alter_room_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='has_table_chairs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='has_wardrobe',
            field=models.BooleanField(default=False),
        ),
    ]
